### ISSUE TITLE
The veteran command bug

### ISSUE THREAD

**Issue by Karim-Besser** [Cortex-Development/cortex-bot#11]
So basically when I invited the bot to my own server and executed `/veteran user:@Karim_B#0001` it says "The application did not respond" here is a screenshot: 
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/102550117/235194237-e35b6e8a-306c-4e52-bf97-dcca2520720b.png">

**Comment by Karim-Besser** [comment]
that was the public one btw but I will try the self hosted one

**Comment by GodOfProDev** [comment]
you should change the veteran role id in the properties file. this is not a bug
