### ISSUE TITLE
Points management commands can be used in other guilds

### ISSUE THREAD

**Issue by matytyma** [Cortex-Development/cortex-bot#21]
You can use the commands to change the points on any server, that's how I have 2023 points now.
You'll have to add a check from what guild is the command being executed or just keep those commands guild based, not global. (As many of them are both, causing duplicity)
![image](https://user-images.githubusercontent.com/100159609/235323664-8d61d441-d2fd-428c-b491-a05cf9e3fb3b.png)

**Comment by KodySimpson** [comment]
Fixed by making bot private
